server:
  port: 8080
spring:
  application:
    name: "franquicia"
  devtools:
    add-properties: false
  datasource:
    url: "jdbc:postgresql://ep-billowing-bird-adeka19q-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require"
    username: "neondb_owner"
    password: "npg_VChQpJ3rG1FH"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: "FranquiciaHikariCP"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  logging:
    level:
      co.com.franquicia: "DEBUG"
      org.springframework.jdbc: "DEBUG"
